
---
title: "decorrelate/ecliars on GTEx v8"
subtitle: ''
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
documentclass: article
output: 
  html_document:
  toc: true
  smart: false
---


<!---

cd /hpc/users/hoffmg01/work/decorrelate
# rm -rf molec_profiling_cache/
ml git pandoc
git pull
R

system("git pull")
rmarkdown::render("vignettes/GTEx.Rmd", output_dir='./', intermediates_dir='./')


# http
# https://hoffmg01.u.hpc.mssm.edu/molec_profiling.html

--->

--->

```{r knit2synapse, eval=FALSE}
library(synapser)
library(knit2synapse)
synLogin()
knit2synapse::createAndKnitToFolderEntity(file = "individual-cohorts/meta_analysis/meta-analysis_sex.Rmd",
                                          parentId ="syn22315403",
                                          folderName = 'Meta-analysis on sex',
                                          overwrite=TRUE, 
                                          knitmd=FALSE)
```


```{r load.packages, echo=FALSE, message=FALSE, results='hide', cache=FALSE}
suppressPackageStartupMessages({
library(variancePartition)
library(limma)
library(edgeR)
library(mvIC)
library(knitr)
library(kableExtra)
library(ggplot2)
library(cowplot)
library(openxlsx)
library(decorrelate)
library(data.table)
})

knitr::opts_chunk$set(
  echo=FALSE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  cache = TRUE,
  cache.lazy = FALSE,  dev = c("png", "pdf"), 
  fig.width=7, fig.height=7)

options(markdown.HTML.stylesheet = 'css/custom.css')
```


# Compare to GTEx
```{r GTEX.voom}

file_SampleAttributesDS = "/sc/arion/projects/CommonMind/data/resources/GTEx/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt"
file_SubjectPhenotypesDS= "/sc/arion/projects/CommonMind/data/resources/GTEx/GTEx_Analysis_v8_Annotations_SubjectPhenotypesDS.txt"
file_counts = "/sc/arion/projects/CommonMind/data/resources/GTEx/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_reads.gct.gz"

gtex_sample = read.delim(file_SampleAttributesDS, header = TRUE, stringsAsFactors = FALSE)
gtex_sample = gtex_sample[gtex_sample$SMTS == 'Brain',]
gtex_sample = gtex_sample[-grep('Cerebell', gtex_sample$SMTSD),]

rnaseq_sample_id = fread(file_counts, header = TRUE, skip = 2, nrows = 1)
gtex_sample = gtex_sample[gtex_sample$SAMPID %in% colnames(rnaseq_sample_id),]

# read count
gtex_count <- fread(file_counts, header = TRUE, skip = 2, select = c('Name', unique(gtex_sample$SAMPID)))
gtex_count = as.data.frame(gtex_count, stringsAsFactors=FALSE)

gtex_count$Name = gsub("^(.*)(\\.\\S+)$", "\\1", gtex_count$Name )
gtex_count = gtex_count[!duplicated(gtex_count$Name), ]
rownames(gtex_count) = gtex_count$Name
gtex_count$Name = NULL
gtex_count = as.matrix(gtex_count)

isexpr = rowSums(cpm(gtex_count)>1) >= 0.3*ncol(gtex_count)
dge = DGEList( gtex_count[isexpr,] )
dge = calcNormFactors(dge, "none")
gtex_log2cpm = cpm(dge, log=TRUE)

# df_voomTrend_GTEx = lapply( unique(gtex_sample$SMTSD), function(Tissue){

#   idx = which( gtex_sample$SMTSD == Tissue)

#   isexpr = rowSums(cpm(gtex_count[,idx])>1) >= 0.3*ncol(gtex_count[,idx])
#   table(isexpr)

#   dge = DGEList( gtex_count[isexpr,idx] )
#   dge = calcNormFactors(dge)

#   vobj = voomWithDreamWeights(dge, ~1, gtex_sample[idx,], plot=FALSE, save.plot=TRUE, BPPARAM=SnowParam(6, progressbar=TRUE))

#   data.frame( key = Tissue, x = vobj$voom.line[['x']], y = vobj$voom.line[['y']])
# })
# df_voomTrend_GTEx = do.call(rbind, df_voomTrend_GTEx)
```

```{r GTEX.voom.plot}
# ggplot(df_voomTrend_GTEx, aes(x, y, color=key)) + geom_line() + theme_bw(15) + theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5), legend.position="bottom") + ylab("sqrt( standard deviation)") + xlab("log2( count size + 0.5 )") + ggtitle("GTEx brain regions") + xlim(2, 22) + ylim(0.45, 1.36)
```

```{r gtex.colors}
# https://genome.ucsc.edu/cgi-bin/hgTables?db=hg19&hgta_track=hgFixed&hgta_group=allTables&hgta_table=hgFixed.gtexTissue

gtexColors = read.csv('/sc/arion/projects/CommonMind/data/resources/GTEx/GTEx_Tissue_colors.csv', header=TRUE)
```

# Standard PCA
```{r PCA}
res.standard = prcomp(scale(t(gtex_log2cpm)), center=FALSE, scale=FALSE)

df = data.frame(res.standard$x)
df = merge(df, gtex_sample, by.x="row.names", by.y="SAMPID")

ggplot(df, aes(PC1, PC2, color=SMTSD)) + geom_point() + theme_classic() + theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5))
ggplot(df, aes(PC2, PC3, color=SMTSD)) + geom_point() + theme_classic() + theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5))
```


# decorrelate
```{r decorrelate}

res.decorr = pca_cor2( t(gtex_log2cpm), 10, maxit=200)
```




```{r plot.decorr}

df = data.frame(res.decorr$U)
rownames(df) = colnames(gtex_log2cpm)
colnames(df) = paste0('PC', 1:10)
df = merge(df, gtex_sample, by.x="row.names", by.y="SAMPID")

ggplot(df, aes(PC1, PC2, color=SMTSD)) + geom_point() + theme_classic() + theme(aspect.ratio=1, plot.title = element_text(hjust = 0.5))

```



```{r test}
library(nnet)

concordance = function(X, group){

  if( length(unique(group)) == 2 ){
    stop("Doesn't work with just 2 groups")
  }

  fit = multinom( group ~ X, trace=FALSE)
  y.pred = predict(fit, type='probs')
  y.true = model.matrix(~0+group)

  sqrt(mean((y.pred - y.true)^2))
}
```







```{r, eval=FALSE}
str(cor.est$decomp)
str(res$decomp)

k = 140
res1 = irlba(resid, nu=k, nv=k)k = 140
res1 = irlba(resid, nu=k, nv=k)


Y = t(gtex_log2cpm)

system.time({
res = eclairs( Y, lambda = .1, k=300)
})

system.time({
res2 = eclairs( Y, lambda = .1, k=300, warmStart=res$decomp)
})

k = 100
system.time({
res <- irlba(Y, nu=k, nv=k)
})

system.time({
res2 <- irlba(Y + 10, nu=k, nv=k, v= res)
})

svd(Y+ 10)$d[1:10]




load("save.RDS")
library(irlba)
library(decorrelate)

dcmp = list(u = warmStart$u[,-140],
            v = warmStart$v[,-140],
            d = warmStart$d[-140])





k = 140
res1 = irlba(resid, nu=k, nv=k, work = 400, verbose=TRUE)
res2 = irlba(resid, nu=k+1, nv=k+1, work = 400, v=warmStart, verbose=TRUE)

str(res1$d)
str(res2$d)
str(warmStart$d)

d = svd(resid)$d





```









