
---
title: "Intuition for data whitening"
subtitle: ''
author: "Developed by [Gabriel Hoffman](http://gabrielhoffman.github.io/)"
date: "Run on `r Sys.time()`"
documentclass: article
output: 
  html_document:
  toc: true
  smart: false
vignette: >
  %\VignetteIndexEntry{Decorrelate}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\usepackage[utf8]{inputenc}
---


<!--- 

rmarkdown::render("intuition.Rmd");

--->



```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  dev = c("png", "pdf"),
  cache = TRUE)
```

```{r run.examples, fig.height=4, fig.width=10}
library(mvtnorm)
library(ggplot2)
library(cowplot)
library(colorRamps)
library(latex2exp)
set.seed(2)

Sigma = matrix(c(1, .9, .9, 2), ncol=2)

Y = rmvnorm(200, c(0, 0), Sigma)

dcmp = eigen(cov(Y))
U = whitening:::makePositivDiagonal(dcmp$vectors)
lambda = dcmp$values

lim = range(Y)

value = (Y %*% U)[,1]

plot_data = function(Y, rotation, rank, lim){

  dcmp = eigen(cov(Y))
  U = whitening:::makePositivDiagonal(dcmp$vectors)
  lambda = dcmp$values

  if( rotation == 1 ){ 
    X = Y

    H = with(eigen(cov(Y)), vectors %*% diag(values))
  }else if( rotation == 2){
    X =  Y %*% U

    H = with(eigen(cov(X)), vectors %*% diag(values))
  
  }else if( rotation == 3){
    X = Y %*% U %*% diag(1/sqrt(lambda))

    H = matrix(c(1,0,0,1), ncol=2)

  }else if( rotation == 4){

    X = Y %*% U %*% diag(1/sqrt(lambda)) %*% t(U)

    H = with(eigen(cov(Y)), vectors)
  }

  df = data.frame(X, rank=scale(rank))

  H = whitening:::makePositivDiagonal(H)

  ggplot(df, aes(X1, X2, color=rank)) + 
    geom_segment(x=0, y=-lim[2], xend=0, yend=lim[2], color="black") +
    geom_segment(x=-lim[2], y=0, xend=lim[2], yend=0, color="black") +
    geom_point(size=.8) + theme_void() + 
    scale_color_gradient2(low="darkblue", mid="grey", high="darkred") + 
    theme(aspect.ratio=1,legend.position="none", plot.title = element_text(hjust = 0.5)) + 
    xlim(lim) + 
    ylim(lim) + 
    geom_segment(x=0, y=0, xend=H[1,1], yend=H[2,1], color="green3", arrow = arrow(length = unit(0.03, "npc")), size=1) + 
    geom_segment(x=0, y=0, xend=H[1,2], yend=H[2,2], color="green3", arrow = arrow(length = unit(0.03, "npc")), size=1)
}


fig1 = plot_data(Y, rotation = 1, rank(value), lim) + ggtitle(TeX('$X$'))
fig2 = plot_data( Y, rotation = 2, rank(value), lim) + ggtitle(TeX('$XU$'))
fig3 = plot_data( Y, rotation = 3, rank(value), lim) + ggtitle(TeX('$XU\\Lambda^{-\\frac{1}{2}}$'))
fig4 = plot_data(Y, rotation = 4, rank(value), lim) + ggtitle(TeX('$XU\\Lambda^{-\\frac{1}{2}}U^T$'))
plot_grid(fig1, fig2, fig3, fig4, ncol=4)




```
