// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dmult_
NumericMatrix dmult_(const NumericMatrix m, const NumericVector v, bool dleft);
RcppExport SEXP _decorrelate_dmult_(SEXP mSEXP, SEXP vSEXP, SEXP dleftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< bool >::type dleft(dleftSEXP);
    rcpp_result_gen = Rcpp::wrap(dmult_(m, v, dleft));
    return rcpp_result_gen;
END_RCPP
}
// dmult_arma
arma::mat dmult_arma(arma::mat M, arma::rowvec v, bool dleft);
RcppExport SEXP _decorrelate_dmult_arma(SEXP MSEXP, SEXP vSEXP, SEXP dleftSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type v(vSEXP);
    Rcpp::traits::input_parameter< bool >::type dleft(dleftSEXP);
    rcpp_result_gen = Rcpp::wrap(dmult_arma(M, v, dleft));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_decorrelate_dmult_", (DL_FUNC) &_decorrelate_dmult_, 3},
    {"_decorrelate_dmult_arma", (DL_FUNC) &_decorrelate_dmult_arma, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_decorrelate(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
