# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmult_ <- function(m, v, dleft) {
    .Call('_decorrelate_dmult_', PACKAGE = 'decorrelate', m, v, dleft)
}

dmult_arma <- function(M, v, dleft = TRUE) {
    .Call('_decorrelate_dmult_arma', PACKAGE = 'decorrelate', M, v, dleft)
}

